# golangci-lint configuration v2
version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosec
    - gocritic
    - revive
    - unconvert
    - unparam
    - bodyclose
    - noctx
    - errname
    - errorlint
    - gochecknoinits
    - goconst
    - godot
    - gocyclo
    - goprintffuncname
    - nilnil
    - nolintlint
    - predeclared
    - whitespace

linters-settings:
  govet:
    disable:
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: true

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gosec:
    excludes:
      - G104

  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst
        - gochecknoinits

  max-issues-per-linter: 0
  max-same-issues: 0
